version: '3.1'

services:

  db:
    image: postgres:13.0
    restart: always
    environment:
      POSTGRES_USER: john
      POSTGRES_PASSWORD: example
      POSTGRES_DB: mdata
    ports:
    - 5432:5432